### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by mpilouk** [leefsmp/forge#1]
I got this build error:
ERROR in ./src/client/Components/Viewer/ViewerManager.js
Module not found: Error: Cannot resolve module 'Viewing.Extension.Storage/Viewing.Extension.Storage' in C:\nodejs\forge\src\client\Components\Viewer
 @ ./src/client/Components/Viewer/ViewerManager.js 32:0-62

It looked like this file has been removed during the last update.

**Comment by leefsmp** [comment]
Hi, this repo is not an official/supported sample, I'm going to retire it. If you are looking for this kind of sample, please take a look at my boiler plates, see project 5 for 2-legged app and project 6 for 3-legged app. Let me know if you have any issue building/deploying those:
[https://github.com/Autodesk-Forge/forge-boilers.nodejs](https://github.com/Autodesk-Forge/forge-boilers.nodejs) 
Thanks,
Philippe.
