### ISSUE TITLE
I can't open the app!

### ISSUE THREAD

**Issue by ycjcl868** [leefsmp/forge#2]
http://localhost:3000

![image](https://user-images.githubusercontent.com/13595509/27116575-a966012e-5104-11e7-8229-62b696cbcc06.png)

![image](https://user-images.githubusercontent.com/13595509/27116579-b703cfb4-5104-11e7-801a-67e2e4d2e7cb.png)

**Comment by leefsmp** [comment]
Sorry this repo is old and not supported anymore, I'm going to delete it. Please use the samples from our official Forge repo: https://github.com/Autodesk-forge
